<?php

/**
 * Implements hook_secure_permissions().
 *
 * Adding permissions for Express Crowdfunding.
 */
function express_crowdfunding_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(

    ),
    'authenticated user' => array(

    ),
    'administrator' => array(
      'administer community funded',
    ),
    'content_editor' => array(

    ),
    'developer' => array(
      'administer community funded',
    ),
    'edit_my_content' => array(

    ),
    'site_owner' => array(
      'administer community funded',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
